### ISSUE TITLE
Compatibility with new ui

### ISSUE THREAD

**Issue by AlexD81** [tachyon-beep/comfyui-simplefeed#2]
Hi, could you pls add compatibility with new ui,  now it overlaps standart toolbar,  where settings button is, so can,t even disable the addon or change its ui position
Thank you

![изображение](https://github.com/user-attachments/assets/ef63ffcc-379c-4baa-a7d4-d13a3b1e4ccb)

**Comment by tachyon-beep** [comment]
I'll check this out this evening. Thanks for letting me know!

**Comment by tachyon-beep** [comment]
![image](https://github.com/user-attachments/assets/c264a931-7817-40c0-9f46-0c6e55fd63ec)

I checked a fix for this into the newui branch, I'll finish testing it tomorrow and move it over.
