### ISSUE TITLE
Non square images are cropped

### ISSUE THREAD

**Issue by NeonSpaceTurtle** [tachyon-beep/comfyui-simplefeed#9]
Need all formats supported, and a zoom in and out feature using scroll wheel would be welcome too.

**Comment by tachyon-beep** [comment]
Thanks for reporting this, I'll take a look!

**Comment by tachyon-beep** [comment]
Just finishing testing, but it should support all kinds of deranged resolutions now.
![image](https://github.com/user-attachments/assets/b929d0ed-2806-4aa6-b31c-d6338a8eb559)

It also supports zoom and pan
![image](https://github.com/user-attachments/assets/51a2ff9e-179d-49d0-90d6-8499220d8deb)

Hoping to get it tested and out in the next day or so.
